apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo

spec:
  volumes:
    - name: shared-data
      emptyDir: {}

  initContainers:
    - name: init-container
      image: nginx:latest
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
  containers:
  - name: nginx
    image: nginx:latest
  ports:
  - containerPort: 80
    volumeMounts:
  - name: shared-data
    mountPath: /usr/share/nginx/html