apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
  labels:
    app: nginx
    env: prod
spec:
  containers:
  - name: write
    image: nginx:latest
    resources:
      limits:
        cpu: "500m"
        memory: "500Mi"
      requests:
        cpu: "200m"
        memory: "200Mi"
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: nginx
    image: nginx:latest
    resources:
      limits:
        cpu: "500m"
        memory: "500Mi"
      requests:
        cpu: "200m"
        memory: "200Mi"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  volumes:
  - name: shared-data
    emptyDir: {}